import { Match, Player } from '../cricket/types';

export const SAMPLE_PLAYERS: Player[] = [
  { id: 'p_1', name: 'Prem' },
  { id: 'p_2', name: 'Rahul' },
  { id: 'p_3', name: 'Amit' },
  { id: 'p_4', name: 'Jay' },
  { id: 'p_5', name: 'Karan' },
  { id: 'p_6', name: 'Rohan' },
  { id: 'p_7', name: 'Vicky' },
  { id: 'p_8', name: 'Sachin' },
  { id: 'p_9', name: 'Virat' },
  { id: 'p_10', name: 'Rohit' },
  { id: 'p_11', name: 'Hardik' },
  { id: 'p_12', name: 'Bumrah' },
];

export const SAMPLE_MATCHES: Match[] = [
  {
    id: 'sample_m1',
    name: 'Weekend Turf Cup Final',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    totalOvers: 8,
    status: 'COMPLETED',
    teamA: {
      id: 't_a',
      name: 'Royal Strikers',
      shortName: 'RST',
      color: '#10b981',
      players: SAMPLE_PLAYERS.slice(0, 6),
    },
    teamB: {
      id: 't_b',
      name: 'Turf Kings',
      shortName: 'TKG',
      color: '#3b82f6',
      players: SAMPLE_PLAYERS.slice(6, 12),
    },
    toss: {
      winnerTeamId: 't_a',
      decision: 'BAT',
    },
    battingFirstTeamId: 't_a',
    bowlingFirstTeamId: 't_b',
    currentInningsNumber: 2,
    winnerTeamId: 't_a',
    resultString: 'Royal Strikers won by 14 runs',
    location: 'Urban Turf Arena, Court 1',
  },
  {
    id: 'sample_m2',
    name: 'Friday Night Box Clash',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    totalOvers: 6,
    status: 'COMPLETED',
    teamA: {
      id: 't_c',
      name: 'Power Hitters',
      shortName: 'PWR',
      color: '#f59e0b',
      players: [
        { id: 'p_13', name: 'Sameer' },
        { id: 'p_14', name: 'Dev' },
        { id: 'p_15', name: 'Yash' },
        { id: 'p_16', name: 'Varun' },
        { id: 'p_17', name: 'Nikhil' },
      ],
    },
    teamB: {
      id: 't_d',
      name: 'Box Blasters',
      shortName: 'BXB',
      color: '#ec4899',
      players: [
        { id: 'p_18', name: 'Tushar' },
        { id: 'p_19', name: 'Aman' },
        { id: 'p_20', name: 'Kunal' },
        { id: 'p_21', name: 'Rishi' },
        { id: 'p_22', name: 'Siddharth' },
      ],
    },
    toss: {
      winnerTeamId: 't_d',
      decision: 'BOWL',
    },
    battingFirstTeamId: 't_c',
    bowlingFirstTeamId: 't_d',
    currentInningsNumber: 2,
    winnerTeamId: 't_d',
    resultString: 'Box Blasters won by 3 wickets (2 balls left)',
    location: 'Prime Turf Hub',
  },
];
